"use client"

import type { Metadata } from "next";
import localFont from "next/font/local";
import { useEffect, useState } from "react";
import "./globals.css";
import { UserProvider } from "../../utils/contexts";
import LogInWrapper from "@/components/LogInWrapper";
import HBMenu from "@/components/HBMenu";
import Footer from "@/components/Footer";
import  CardsContainer  from "@/components/CardsContainer";

import Logo from "@/components/Logo";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false); 
    }, 2100); 

    return () => clearTimeout(timer);
  }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {loading ? (<>
          <div
            id="splash-screen"
            className="fixed inset-0 flex items-center justify-center bg-pt-primary z-50 transition-opacity duration-1000 ease-out opacity-100"
          >
            <div className="text-pt-secondary text-3xl md:text-7xl font-bold animate-zoom flex flex-col justify-center items-center"><Logo width={"200px"} height={"200px"} color={"#E0A73F"} /> <p>Pandorum</p>  </div>
          </div>
          
        </>
          
        ) : (
          <UserProvider>
            <HBMenu />
            <LogInWrapper>{children}</LogInWrapper>
            <CardsContainer />
            <Footer />
          </UserProvider>
        )}
      </body>
    </html>
  );
}
