"use client"

import type { Metadata } from "next";
import localFont from "next/font/local";
import { useEffect, useState } from "react";
import "./globals.css";
import { UserProvider } from "../../utils/contexts";
import LogInWrapper from "@/components/LogInWrapper";
import HBMenu from "@/components/HBMenu";
import Footer from "@/components/Footer";
import  CardsContainer  from "@/components/CardsContainer";
import SplashScreen from "@/components/SplashScreen";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  const [loading, setLoading] = useState(true); 

  useEffect(() => {
    
      setTimeout(() => {
        setLoading(false);
      }, 2100); 
      
    
  }, []);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {loading ? (
          <SplashScreen />
        ) : (
          <UserProvider>
            <HBMenu />
            <LogInWrapper>{children}</LogInWrapper>
            <CardsContainer />
            <Footer />
          </UserProvider>
        )}
      </body>
    </html>
  );
}
